### ISSUE TITLE
[BUG] 成语接龙handler里的message不会变

### ISSUE THREAD

**Issue by whyour** [ReiKohaku/piggy-bro#3]
**描述您的问题**
对BUG进行一个清晰而简洁的描述

**如何复现**
复现该行为的步骤

**期望行为**
对您所期望行为的一个清晰而简洁的描述

**截图或日志**
如果可以，请附带截图或日志
```text

```

**环境**
 - 系统：[例如Windows 10、Ubuntu 20.04等]

**备注**
其它有关问题的注解

**Comment by ReiKohaku** [comment]
可否描述得清楚一些，不太能理解你提出的Bug是什么

**Comment by ReiKohaku** [comment]
由于您没有给出问题的详细描述，我先把这个issue关闭了，如果有问题还请继续回复。
